"""remove giveup column from statistics

Revision ID: 3c0cbed04a90
Revises: 804005e79950
Create Date: 2020-12-22 19:57:57.317418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0cbed04a90'
down_revision = '804005e79950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.drop_column('giveup')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giveup', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
