"""add statistics

Revision ID: 9e957035487a
Revises: b03c62460f13
Create Date: 2017-10-25 09:02:32.613922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e957035487a'
down_revision = 'b03c62460f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('lose', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('draw', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('giveup', sa.Integer(), nullable=False, server_default='0'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'opponent_id')
    )
    op.create_index('account_statistics', 'statistics', ['account_id', 'opponent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('account_statistics', table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###
